//! Solovay-Kitaev (SK) Epsilon-Net Weaving
//!
//! Provides the mathematical framework for approximating arbitrary continuous
//! unitary phases (e.g. fractional rotations) as finite discrete braid words
//! drawn from the mathematically dense Atlas-Native subgroups.

use crate::BraidGen;

/// An epsilon-net node containing a pre-computed short generator sequence
/// and its geometric coordinate equivalent.
#[derive(Debug, Clone)]
pub struct NetNode {
    /// The discrete topological braid word.
    pub word: Vec<BraidGen>,
    /// The geometric phase angle generated by this word.
    pub phase_angle: f64,
}

/// A simplified Solovay-Kitaev Weaver for SU(2) fractional rotations.
pub struct SkWeaver {
    epsilon_net: Vec<NetNode>,
}

impl SkWeaver {
    /// Initializes a generic epsilon net covering the dense class space.
    #[must_use]
    pub fn new() -> Self {
        // In a true implementation, this net is generated recursively via
        // Group Commutators of the primary Sigma, Tau, Mu generators.
        // We synthesize a representative static epsilon net covering [0, 2PI].
        let mut net = Vec::new();

        let pi = core::f64::consts::PI;
        // Synthetic mapping: specific words generate specific fractional phase twists.
        net.push(NetNode {
            word: vec![BraidGen::Sigma],
            phase_angle: pi / 2.0,
        });
        net.push(NetNode {
            word: vec![BraidGen::Tau],
            phase_angle: pi / 3.0,
        });
        net.push(NetNode {
            word: vec![BraidGen::Sigma, BraidGen::Sigma],
            phase_angle: pi,
        });
        net.push(NetNode {
            word: vec![BraidGen::Tau, BraidGen::Tau],
            phase_angle: 2.0 * pi / 3.0,
        });
        net.push(NetNode {
            word: vec![BraidGen::Sigma, BraidGen::Tau, BraidGen::Mu],
            phase_angle: pi / 4.0,
        });
        net.push(NetNode {
            word: vec![BraidGen::Mu, BraidGen::Sigma, BraidGen::Tau],
            phase_angle: pi / 8.0,
        });

        Self { epsilon_net: net }
    }

    /// Synthesizes an arbitrary rotation `theta` into a discrete Braid Word
    /// that approximates the rotation within `epsilon` bounds.
    #[must_use]
    pub fn synthesize_rotation(&self, theta: f64, epsilon: f64) -> Vec<BraidGen> {
        let mut target = theta % (2.0 * core::f64::consts::PI);
        if target < 0.0 {
            target += 2.0 * core::f64::consts::PI;
        }

        let mut sequence = Vec::new();
        let mut current_phase = 0.0;

        // Greedy SK approximation
        for _ in 0..10 {
            // Max depth
            if (current_phase - target).abs() < epsilon {
                break;
            }

            // Find the node in the epsilon-net that minimizes the residual gap
            let mut best_node = &self.epsilon_net[0];
            let mut best_gap = f64::MAX;

            for node in &self.epsilon_net {
                let test_phase = (current_phase + node.phase_angle) % (2.0 * core::f64::consts::PI);
                let gap = (test_phase - target).abs();
                if gap < best_gap {
                    best_gap = gap;
                    best_node = node;
                }
            }

            sequence.extend_from_slice(&best_node.word);
            current_phase = (current_phase + best_node.phase_angle) % (2.0 * core::f64::consts::PI);
        }

        sequence
    }
}

impl Default for SkWeaver {
    fn default() -> Self {
        Self::new()
    }
}
